### ISSUE TITLE
About angle2pose？

### ISSUE THREAD

**Issue by xuyaojian123** [Ruyi-Zha/r2_gaussian#11]
在这里您说描述了旋转过程 [issue 9](https://github.com/Ruyi-Zha/r2_gaussian/issues/9#issuecomment-2452224124)，但按照您说的相机坐标系，经过旋转两次旋转后的坐标系方向x,y,z和世界坐标系不一样，您能帮我看看哪里出了问题嘛？

![image](https://github.com/user-attachments/assets/51fa74ce-5bdf-432a-8a74-e0d3a92a0449)

**Comment by immortalmin** [comment]
应该是旋转世界坐标系得到相机坐标系

**Comment by xuyaojian123** [comment]
> 应该是旋转世界坐标系得到相机坐标系

应该不是，angle2pose求的是c2w矩阵，应该是旋转相机坐标系到世界坐标系。

**Comment by immortalmin** [comment]
我认为得到的c2w矩阵，它的列向量其实就是相机坐标系的基在世界坐标系中的表示。
你可以通过一个简单的c2w矩阵来验证这一点，比如只是绕Z轴旋转90度
![image](https://github.com/user-attachments/assets/c02868c9-85ef-4bb1-a479-11ae49f66b4b)
那么如果用这个矩阵左乘以相机坐标系中的任意一个点，得到的其实就会是这个点在世界坐标系中的表示。
我讲得有点不太清楚，你可以参考一下3Blue1Brown关于基变换的[视频](https://www.bilibili.com/video/BV1Ls411b7r2/?share_source=copy_web&vd_source=78317a2a3150f147c7ffdcc65890f2c5)
如果有哪里错误或者不理解，敬请指出。

**Comment by xuyaojian123** [comment]
> 我认为得到的c2w矩阵，它的列向量其实就是相机坐标系的基在世界坐标系中的表示。 你可以通过一个简单的c2w矩阵来验证这一点，比如只是绕Z轴旋转90度 ![image](https://private-user-images.githubusercontent.com/42803282/384701644-c02868c9-85ef-4bb1-a479-11ae49f66b4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNTQ2MjksIm5iZiI6MTczMTI1NDMyOSwicGF0aCI6Ii80MjgwMzI4Mi8zODQ3MDE2NDQtYzAyODY4YzktODVlZi00YmIxLWE0NzktMTFhZTQ5ZjY2YjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDE1NTg0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlZmM0NzJmNzJmMzE5YTMzMmVjMzZiNDcyMDA4NzBiMDEzMTIxZGFkNDQyYmQzYWQzMTAxNGYyMTA1OGU1NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7eqln3xVe4keVtIGfzYBhxFTehPBnGznVre5BzJSREo) 那么如果用这个矩阵左乘以相机坐标系中的任意一个点，得到的其实就会是这个点在世界坐标系中的表示。 我讲得有点不太清楚，你可以参考一下3Blue1Brown关于基变换的[视频](https://www.bilibili.com/video/BV1Ls411b7r2/?share_source=copy_web&vd_source=78317a2a3150f147c7ffdcc65890f2c5) 如果有哪里错误或者不理解，敬请指出。

嗯嗯，你说的这些我之前有些了解。刚才按照你说的，如果是旋转世界坐标系的话，方向就和相机坐标系对上了。

**Comment by xuyaojian123** [comment]
c2w矩阵之前我明白的是求相机坐标系的点在世界坐标系的表示，然后我也以为是把相机坐标系转到世界坐标系的方向上。

**Comment by Ruyi-Zha** [comment]
感谢@immortalmin的解答, c2w是相机在世界坐标系下的表示，其旋转矩阵也是在世界坐标系下描述的，所以是旋转世界坐标系。

**Comment by xuyaojian123** [comment]
感谢！
