### ISSUE TITLE
The errors of generate data

### ISSUE THREAD

**Issue by zyuxiang0822** [Ruyi-Zha/r2_gaussian#14]
Your work is excellent. However, when I ran your code to generate data, I encountered a problem and hope you can help me. Thank you. The `vol_gt` was generated normally, but an error occurred when generating projection data:

python data_generator/synthetic_dataset/generate_data.py \
  --vol data_generator/synthetic_dataset/volume_processed \
  --scanner data_generator/synthetic_dataset/scanner/cone_beam.yml \
  --output data/synthetic_dataset/cone_ntrain_75_angle_360 \
  --n_train 75 \
  --n_test 100 \
  --device 0 
Generate data for case 1_beetle_cone
Traceback (most recent call last):
  File "/home/ubuntu/r2_gaussian/data_generator/synthetic_dataset/generate_data.py", line 122, in <module>
    main(args)
  File "/home/ubuntu/r2_gaussian/data_generator/synthetic_dataset/generate_data.py", line 55, in main
    projs_train = tigre.Ax(
  File "/home/ubuntu/r2_gaussian/data_generator/synthetic_dataset/tigre/utilities/Ax.py", line 35, in Ax
    return _Ax_ext(img, geox, geox.angles, projection_type, geox.mode, gpuids=gpuids)
  File "tigre/utilities/cuda_interface/_Ax.pyx", line 88, in _Ax._Ax_ext
TypeError: 'numpy.float32' object cannot be interpreted as an integer

**Comment by Ruyi-Zha** [comment]
I reran `generate_data.py` and was able to generate the dataset successfully. Are you using your own volume data or ours? Based on the error information, it seems to be related to TIGRE. I suggest reinstalling TIGRE (we are using version 2.3) and giving it another try.

```
wget https://github.com/CERN/TIGRE/archive/refs/tags/v2.3.zip
unzip v2.3.zip
pip install TIGRE-2.3/Python --no-build-isolation
```

**Comment by zyuxiang0822** [comment]
Thank you very much for your help; the issue has been resolved. You were right—it was a problem with TIGRE version 2.3. When I installed it, I forgot to include --no-build-isolation in the command pip install ./TIGRE-2.3/Python --no-build-isolation.

**Comment by Ruyi-Zha** [comment]
You're welcome :)
