### ISSUE TITLE
Empty simple-knn

### ISSUE THREAD

**Issue by JixiangChen-Jimmy** [Ruyi-Zha/r2_gaussian#15]
Dear authors,

Thanks for sharing your awesome work. During downloading your code, I found that the simple-knn folder is empty. And I can not successfully install the rasterizer with error: 

r2_gaussian/submodules/xray-gaussian-rasterization-voxelization/cuda_rasterizer/rasterizer_impl.cu:23:10: fatal error: glm/glm.hpp: No such file or directory
       23 | #include <glm/glm.hpp>
          |          ^~~~~~~~~~~~~
    compilation terminated.

Do you have some suggestions in addressing this issue?

**Comment by Ruyi-Zha** [comment]
Hi. Our code includes submodules from other GitHub repositories (`simple-knn` and `glm`). Downloading the `zip` file directly will not include these submodules. To ensure everything is downloaded correctly, please use the following command with the `--recursive` flag.

```sh
git clone https://github.com/Ruyi-Zha/r2_gaussian.git --recursive
```
