### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by LarkLeeOnePiece** [Ruyi-Zha/r2_gaussian#17]
Wonderful job! I am trying to see whether this can work for Cryo-ET data. I have one question about the format of the data. In paper 3.1, we know we need to transfer the data into logarithmic space(Lineraized process), so when I initialize the Gaussians, I think the densities are in logarithmic space, right? Also, for the projections, we also need to linearize them, am I correct?

**Comment by Ruyi-Zha** [comment]
Hi. Yes, the projections should be transferred to logarithmic space (black background, white tissue). The densities are defined in this space, such that the rendering process is the integration of densities along the ray.

**Comment by LarkLeeOnePiece** [comment]
Thanks!
