### ISSUE TITLE
Question about data generation

### ISSUE THREAD

**Issue by risako-tt** [Ruyi-Zha/r2_gaussian#19]
Thank you for sharing your wonderful work!

I have a question about the projected data generation from raw data.
I'm trying to create training data from synthetic volume data with parallel mode using `data_generator/synthetic_dataset/generate_data.py`. 
But I'm not sure how to set the detector and image parameters on the `data_generator/synthetic_dataset/scanner/parallel_beam.yml` file.
Could you please tell me the units of the following parameters?
	- DSD, DSO
	- sDetector
	- sVoxel
Do they indicate the value in meters or millimeters?

**Comment by Ruyi-Zha** [comment]
Hi, the synthetic dataset does not have physical units. We just use some example value ranges used in TIGRE. You can assign any units you prefer, but ensure that the X-ray images and scanner configuration follow a consistent unit system.

**Comment by risako-tt** [comment]
Hi,
Thank you very much for your response! I understand the synthetic dataset does not have units.

However, another question arose. In the real dataset, there is a variable called `object_scale`, which is multiplied by the actual DSD and DSO values. The description of the `object_scale` in `data_generator/real_dataset/generate_data.py` says that it is "Rescale the whole scene to similar scales as the synthetic data". The `object_scale` description of the `data_generator/real_dataset/generate_data_all.py` says "Subsample number of views as sparse-view".

The DSD and DSO values written in the real data configuration file and the `meta_data.json` are different because the `object_scale` is multiplied. But how should I set this value? What does the default number 50 mean?

It may be a trivial thing, but I hope to hear from you.

**Comment by Ruyi-Zha** [comment]
Hi, `object_scale` was empirically set during our early exploration to align the spatial range with synthetic data. However, since our method scales the scene when loading data [here](https://github.com/Ruyi-Zha/r2_gaussian/blob/fcde922d001a5de028d55a3a3f20bdfaf5ba60a7/r2_gaussian/dataset/dataset_readers.py#L62), I think this parameter might no longer be necessary.

The description in `generate_data_all.py` is outdated. Please ignore it and I will update that later on.

**Comment by risako-tt** [comment]
Thank you very much for your kind response!
