### ISSUE TITLE
about code

### ISSUE THREAD

**Issue by hutouhunao1** [Ruyi-Zha/r2_gaussian#2]
wonderful work！！！Please when update the code！
Thanks

**Comment by Ruyi-Zha** [comment]
Thanks for your interest in our work. We will release the code upon paper acceptance.

**Comment by Erhushenshou** [comment]
Have your paper get accepted? Hope to see the source code soon.

**Comment by Ruyi-Zha** [comment]
Hi, our work has been accepted to NeurIPS 2024. We're currently cleaning up the repository, and the code is expected to be released later this month. Stay tuned!

**Comment by tlxhlll** [comment]
Hi, congratulations! 
When will you release the code?

**Comment by Ruyi-Zha** [comment]
Hi all, we have released the code, data, and models. Welcome to have a try!
