### ISSUE TITLE
Resolution control

### ISSUE THREAD

**Issue by jason5306** [Ruyi-Zha/r2_gaussian#20]
Hi Ruyi, Thanks for your amazing work. I tried to run your code on my own data and got some problems. I followed your data preprocessing pipeline for synthetic data and normalized the volume to [0, 1] before generating projections. However, with the default initialization and training parameters, I got a blurry recon volume. The resolution of my data is 2 mm in voxel, I wonder what parameters are related to resolution control. Thank you!

**Comment by Ruyi-Zha** [comment]
Hi, could you please share more details? For example, the number of projections, volume resolution, what your volume looks like, the training curve, the total number of Gaussians after training, etc. My initial guess for the blurry results is: (1) The projections do not fully cover the entire volume for reconstruction, (2) There are too few projections.

**Comment by jason5306** [comment]
Yes I did a thorough check on the code and it turns out to be the issue of
the projections that do not cover the entire volume. Thank you so much for
your instructions!!
