### ISSUE TITLE
A scale difference between ray space and real world space

### ISSUE THREAD

**Issue by immortalmin** [Ruyi-Zha/r2_gaussian#4]
Hi, Excellent work!
I want to ask why there should be a scale difference between ray space and real world space? 
> https://github.com/Ruyi-Zha/r2_gaussian/blob/ab2edc48d250c3177802bd4f327f02d33f66272c/r2_gaussian/submodules/xray-gaussian-rasterization-voxelization/cuda_rasterizer/forward.cu#L139-L142

**Comment by Ruyi-Zha** [comment]
Thank you for your interest in our work. 

The X-ray projection physically records the integration of density along the X-ray path, so the pixel values correlate with real-world scales.

Following Gaussian Splatting, we transform Gaussians from world space into [normalized device coordinates](https://www.songho.ca/opengl/gl_projectionmatrix.html) (NDC, or ray space) for rasterization. NDC is a scaled [-1, 1]^3 cube, as shown below. Therefore, there is a scale problem to correctly render X-ray projections.

There are two solutions. One is to include the scale as part of the rasterization input. The other is to scale the entire scene (including geometry and X-ray projections) into the [-1, 1]^3 cube. For simplicity, we have opted for the latter. You can find relevant code [here](https://github.com/Ruyi-Zha/r2_gaussian/blob/ab2edc48d250c3177802bd4f327f02d33f66272c/r2_gaussian/dataset/dataset_readers.py#L62).

_Perspective Frustum and Normalized Device Coordinates (NDC)_
![image](https://github.com/user-attachments/assets/7c648cb2-500e-4a2b-b740-055309141abf)

**Comment by immortalmin** [comment]
Thank you for your prompt reply.
I have some other opinions on this.

The key points of the following analysis are:
1. The Jacobian matrix simply transforms the Gaussian covariance matrix into ray space, which is a different concept from NDC.
2. Ray space and screen space may only differ by one translation on the xy coordinate system.
3. Discussing rasterization in ray space.
---
From the Jacobian matrix, 
https://github.com/Ruyi-Zha/r2_gaussian/blob/0dee9fa50c2ee8ad0bd346b342cb1b154b75f7c9/r2_gaussian/submodules/xray-gaussian-rasterization-voxelization/cuda_rasterizer/forward.cu#L110-L114
the transformation performed on Gaussian in camera space is 
<img width="386" alt="image" src="https://github.com/user-attachments/assets/c70dce89-c88d-4523-bff5-f16697bdaf75">
which is a perspective matrix.
So Gaussian was only converted to ray space and not scaled to NDC.
To scaled to NDC, an additional transformation is needed. Something like this
<img width="908" alt="image" src="https://github.com/user-attachments/assets/6ff7b1de-e7d4-4424-9e71-25c023fbce90">

In ray space, the xy coordinate is actually the xy component of the intersection point between the ray and **the projection plane**, and the unit should be pixels like focal.
We can infer from the following code that the unit of focal is pixels
https://github.com/Ruyi-Zha/r2_gaussian/blob/0dee9fa50c2ee8ad0bd346b342cb1b154b75f7c9/r2_gaussian/submodules/xray-gaussian-rasterization-voxelization/cuda_rasterizer/rasterizer_impl.cu#L219-L220
But the difference from the xy coordinate in screen space is that there is one less translation. That can be expressed as
<img width="245" alt="image" src="https://github.com/user-attachments/assets/28559f87-bf99-40f8-80cb-cca557992911">
On the other hand, the mean of Gaussian was transformed into screen space, and d was calculated based on the position of pixel and the mean of Gaussian.
We can calculate d in ray space
<img width="642" alt="image" src="https://github.com/user-attachments/assets/c33168ba-176b-4ad2-95e6-be22675e2e4b">
which is same as d in screen space.
Therefore, from the perspective of ray space, the implementation of rasterization does make sense.

**Comment by Ruyi-Zha** [comment]
Thanks for your inspiring discussion. I somehow come up with other ideas.

Look at affine matrix J. 
 https://github.com/Ruyi-Zha/r2_gaussian/blob/0dee9fa50c2ee8ad0bd346b342cb1b154b75f7c9/r2_gaussian/submodules/xray-gaussian-rasterization-voxelization/cuda_rasterizer/forward.cu#L110-L114

We scale the `x` and `y` axes by `focal_x` and `focal_y`, respectively, while leaving the `z` axis unchanged. As a result, the scale of `z` remains consistent with the camera space. Since the transformation `W` from world space to camera space involves only rotation and translation, the scales of camera space and world space are equivalent. Therefore, `mu`, which depends solely on `z`, reflects the world scale.

Note that with `focal_x` and `focal_y`, the `x` and `y` axes have been converted to screen space (or ray space, based on your great opinions) for further computation.

Although it may seem strange that matrix entries have different scales, I think we should keep the code still as it has proven to work LOL.

**Comment by immortalmin** [comment]
While I may have a slightly different take on this, I think it’s great that we can discuss it from different angles.

As I mentioned before, camera space and ray space are related by the mapping $x = \phi(t)$ 
<img width="383" alt="image" src="https://github.com/user-attachments/assets/ecffdc0e-414f-4226-bc2c-43428f91aafc">
Therefore, the `z` will become the distance from the point on the viewing ray to the center of the projection, which is consistent with the description in [EWA Splatting](https://www.cs.umd.edu/~zwicker/publications/EWASplatting-TVCG02.pdf)(see section 4.1 and section 6.2.2).
<img width="646" alt="image" src="https://github.com/user-attachments/assets/c6bceaf0-73df-4c9f-bc64-a2041eb8c826">
This can also be verified through the Jacobian matrix,
<img width="605" alt="image" src="https://github.com/user-attachments/assets/075daeac-1baf-4920-9693-f163d9d6d945">

I also have some questions about
> Therefore, `mu`, which depends solely on `z`, reflects the world scale.

I guess what you mean is that `x` and `y` won't affect `mu`. But  the Jacobian matrix is affected by `x` and  `y`, which in turn affect `cov` and `mu`.

**Comment by Ruyi-Zha** [comment]
> Therefore, `mu`, which depends solely on `z`, reflects the world scale.

I mean focal lengths $f_x$ and $f_y$ won't affect $\mu$.


The tricky thing is that we combine camera-to-ray and ray-to-screen into one Jacobian matrix $J$. We can see that $J$ in our [code](https://github.com/Ruyi-Zha/r2_gaussian/blob/0dee9fa50c2ee8ad0bd346b342cb1b154b75f7c9/r2_gaussian/submodules/xray-gaussian-rasterization-voxelization/cuda_rasterizer/forward.cu#L110-L114) is actually 

$$
J=FJ_{ewa} ,F=\begin{bmatrix}
f_x & 0 & 0 \\
0 & f_y & 0 \\
0 & 0 & 1 
\end{bmatrix}.
$$

where $J_{ewa}$ is camera-to-ray matrix in Eq. (29) [EWA splatting](https://www.cs.umd.edu/~zwicker/publications/EWASplatting-TVCG02.pdf).
The new 3D covairance matrix is therefore

$$
\Sigma_{screen}=FJ_{ewa}W\Sigma W^T J_{ewa}^T F^T.
$$

Let's define 

$$
\Sigma_{ray}=J_{ewa}W\Sigma W^T J_{ewa}^T=\begin{bmatrix}
a & b & c \\
b & d & e \\
c & e & f 
\end{bmatrix}.
$$

Therefore we have

$$
\Sigma_{screen}=\begin{bmatrix}
f_x^2 a & f_x f_y b & f_x c \\
f_x f_y b & f_y^2 d & f_y e \\
f_x c & f_y e & f 
\end{bmatrix}.
$$

The determinant of $\Sigma_{screen}$ is  $|\Sigma_{screen}|=f_x^2 f_y^2 (adf+2bce-ae^2-fb^2-dc^2)$.

The 2D covariance matrix $\Sigma_{2D}$ is simply the 2x2 part of $\Sigma_{screen}$. Its determinant is $|\Sigma_{2D}|=f_x^2 f_y^2 (ad-b^2)$.

Now let's compute bias factor $\mu$.

$$
\mu=\sqrt{\frac{2\pi |\Sigma_{screen}|}{|\Sigma_{2D}| }}=\sqrt{\frac{2\pi*(adf+2bce-ae^2-fb^2-dc^2)}{ad-b^2}}.
$$

We can see that $f_x$ and $f_y$ are eliminated, which means $\mu$ is not related to focal length.

**Comment by immortalmin** [comment]
Based on your deduction, I agree with $f_x$ and $f_y$ won't affect $\mu$.
