### ISSUE TITLE
Orthographic camera

### ISSUE THREAD

**Issue by tlxhlll** [Ruyi-Zha/r2_gaussian#5]
Congratulations to you! I have a question: why did you choose to use an orthographic camera instead of a perspective camera?

**Comment by Ruyi-Zha** [comment]
Hi, we support both orthographic (parallel beam CT) and perspective (cone beam CT) cameras. You can find relevant code [here](https://github.com/Ruyi-Zha/r2_gaussian/blob/ab2edc48d250c3177802bd4f327f02d33f66272c/r2_gaussian/gaussian/render_query.py#L123C14-L123C30) and [here](https://github.com/Ruyi-Zha/r2_gaussian/blob/ab2edc48d250c3177802bd4f327f02d33f66272c/r2_gaussian/dataset/dataset_readers.py#L134).

Our datasets currently use perspective cameras (cone beam). To switch to orthographic mode, change the `mode` setting in `meta_data.json` from `cone` to `parallel`.
