### ISSUE TITLE
volume show

### ISSUE THREAD

**Issue by shenao1994** [Ruyi-Zha/r2_gaussian#7]
Hi! I am very interested in your visualization method. I found some visualization methods in the **plot_utils.py** file. But I want to achieve the effect shown in the picture. Is it showing a projection image from a certain perspective, but I feel it has a strong sense of three dimensionality.
![微信截图_20241030161204](https://github.com/user-attachments/assets/c6862327-074d-4a8f-b176-ef2bba238c38)

**Comment by Ruyi-Zha** [comment]
Hi, the image is rendered with pyvista, while the red and blue boxes are cropped by myself. I will update a simple script about how to render this image later :)

**Comment by Ruyi-Zha** [comment]
Hi, I have uploaded the [script](https://github.com/Ruyi-Zha/r2_gaussian/blob/89111972c322a4b466b5d910f502d83e96909418/scripts/plot_volume.py#L1). You are welcome to have a try.

**Comment by shenao1994** [comment]
> Hi, I have uploaded the [script](https://github.com/Ruyi-Zha/r2_gaussian/blob/89111972c322a4b466b5d910f502d83e96909418/scripts/plot_volume.py#L1). You are welcome to have a try.

Thank you!
