### ISSUE TITLE
符号小错误？

### ISSUE THREAD

**Issue by xuyaojian123** [Ruyi-Zha/r2_gaussian#9]
红色箭头的符号没对应上吧？另外我想请问下，你这里W表示的旋转矩阵是如何推导的呢？不是应该绕z轴旋转吗？

![image](https://github.com/user-attachments/assets/64cb9599-fb2c-4887-94e1-4b7c9a87c02a)

![image](https://github.com/user-attachments/assets/f44699f2-ad91-4ccd-bed8-a01481ed10cc)

![image](https://github.com/user-attachments/assets/601fbc38-8eca-4d68-a7ec-7bf4a6398227)

**Comment by immortalmin** [comment]
你可以参考这里的代码
https://github.com/Ruyi-Zha/r2_gaussian/blob/e894f055b231d64ea8a0ce868acb3ec292987410/r2_gaussian/dataset/dataset_readers.py#L156-L191
把三个矩阵乘起来就能得到上面的结果
然后可能还要考虑这里的转置
https://github.com/Ruyi-Zha/r2_gaussian/blob/e894f055b231d64ea8a0ce868acb3ec292987410/r2_gaussian/dataset/dataset_readers.py#L265-L267

**Comment by Ruyi-Zha** [comment]
> 红色箭头的符号没对应上吧

Yes this is a typo. $\phi$ should be $\theta$.

> 旋转矩阵是如何推导

Thanks for the reply of @immortalmin, which is exactly the answer. Note that in [angle2pose](https://github.com/Ruyi-Zha/r2_gaussian/blob/e894f055b231d64ea8a0ce868acb3ec292987410/r2_gaussian/dataset/dataset_readers.py#L156-L191), the output pose is camera-to-world, while $W$ is world-to-camera, so there will be an additional transpose (inverse) [here](https://github.com/Ruyi-Zha/r2_gaussian/blob/e894f055b231d64ea8a0ce868acb3ec292987410/r2_gaussian/dataset/dataset_readers.py#L122), leading to Eq. 10 in the paper.

Our coordinate system matches those used in NAF and SAX-NeRF, as shown in the diagram below. You can see the camera (source) rotation is not a simple rotation along the world z-axis, as the camera's z-axis is oriented toward the world center. The rotation can be achieved by (1) rotating -90 degrees around the world x-axis, (2) rotating 90 degrees around the world z-axis, and (3) rotating $\theta$ degrees around the world z-axis.


![image](https://github.com/user-attachments/assets/1f98b1fb-8895-40f6-8e8c-5a492e5ff054)

**Comment by immortalmin** [comment]
Yes, my answer about transpose was incorrect. Please refer to here
> Note that in [angle2pose](https://github.com/Ruyi-Zha/r2_gaussian/blob/e894f055b231d64ea8a0ce868acb3ec292987410/r2_gaussian/dataset/dataset_readers.py#L156-L191), the output pose is camera-to-world, while $W$ is world-to-camera, so there will be an additional transpose (inverse) [here](https://github.com/Ruyi-Zha/r2_gaussian/blob/e894f055b231d64ea8a0ce868acb3ec292987410/r2_gaussian/dataset/dataset_readers.py#L122), leading to Eq. 10 in the paper.
